:uri-teamcity-settings: https://www.jetbrains.com/help/teamcity/kotlin-dsl.html
:uri-teamcity-plugin: https://plugins.jetbrains.com/docs/teamcity/
:uri-gradle: https://gradle.org/[Gradle]
:uri-blog-post: https://blog.jetbrains.com/teamcity/2020/09/creating-teamcity-project-templates-with-kotlin-dsl-context-parameters/
:uri-apache-license: http://www.apache.org/licenses/LICENSE-2.0.html[Apache License, Version 2.0]
:project-name: teamcity-plugin-build-settings
:uri-github: https://github.com
:uri-github-project: {uri-github}/rodm/{project-name}
:uri-github-actions: {uri-github-project}/actions
:uri-github-status: {uri-github-actions}/workflows/build.yml/badge.svg

= TeamCity Plugin Build Settings

This project contains TeamCity {uri-teamcity-settings}[Kotlin DSL settings] to build
a {uri-teamcity-plugin}[TeamCity plugin] using {uri-gradle}.

image:{uri-github-status}?branch=main["Build Status", link="{uri-github-actions}"]

The settings for a project can be configured with the following context parameters

Required context parameters

* `vcs.name` - A name for the VCS root
* `vcs.url` - A Git URL to the project containing the TeamCity plugin code
* `teamcity.api.versions` - A comma separated list of TeamCity versions, e.g. `2018.1,2020.2`

For each version listed in the `teamcity.api.versions` parameter a build configuration is
created to build the plugin code using that version of the TeamCity API.

Optional context parameters

* `vcs.branch` - A name for the branch to use. The default is `master`.
* `vcs.auth.method` - A name for the authentication method to use to access the VCS root. The default is `anonymous`.
* `artifact.paths` - A comma separated or newline separated list of paths to search for artifacts to publish.
https://www.jetbrains.com/help/teamcity/2024.07/?Configuring+General+Settings#ConfiguringGeneralSettings-ArtifactPaths
* `gradle.tasks` - A string of alternative Gradle tasks to run for build configurations excluding the report
configuration. The default is `clean build`.
* `gradle.options` - A string of additional options to be passed to the Gradle command. The default is an empty string.
* `agent.requirements` - A comma separated list of either build id and requirement or requirement. If the build id is
not specified then the requirement applies to all build configurations. The default is no agent requirement, e.g. `Build1=linux,docker`, this example creates all build configurations requiring Docker and `Build1` to require Docker and Linux.
* `report.task` - A task name to be run be the code quality report build configuration. The default is `sonar`.

A list of VCS authentication method names

* `anonymous` - The VCS root requires no authentication.
* `password` - The VCS root requires a username and password to access. The context parameters `vcs.auth.username` and
`vcs.auth.password` are required.
* `uploadedkey` - The VCS root requires an uploaded key, username, and passphrase to access. The context parameters
`vcs.auth.uploadedkey`, `vcs.auth.username`, and `vcs.auth.passphrase` are required.

A list of VCS authentication parameters

* `vcs.auth.username` - The username used to access the VCS root.
* `vcs.auth.password` - The password used to access the VCS root.
* `vcs.auth.uploadedkey` - The uploaded key used to access the VCS root.
* `vcs.auth.passphrase` - The passphrase used to access the VCS root.

A list of requirement names

* `linux` - A build configuration requires a build agent running on Linux
* `macos` - A build configuration requires a build agent running on macOS
* `solaris` - A build configuration requires a build agent running on Solaris
* `windows` - A build configuration requires a build agent running on Windows
* `docker` - A build configuration requires a build agent with Docker.

The build configuration ids depend on the number of TeamCity API versions specified in the parameter `teamcity.api.versions`,
the first configuration is `Build1`, the second is `Build2` etc. The reporting configuration has the id `ReportCodeQuality`.

Invalid build ids and requirement names throw an exception causing the `teamcity-configs:generate` task to fail.

This project based on the ideas from the following blog post
{uri-blog-post}[Creating TeamCity project templates with Kotlin DSL context parameters]

== License

This plugin is available under the {uri-apache-license}.
